name: Deploy UrbanCmp Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: List all Docker images
        run: docker ps -a -q
      - name: Build Docker Image
        run: docker build -t sayan006/urbancmp-backend .
      - name: Publish Image in Docker Hub
        run: docker push sayan006/urbancmp-backend:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull sayan006/urbancmp-backend:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name urbancmp-backend-container-1 -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' sayan006/urbancmp-backend